name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install zip
      run: sudo apt install zip

    - name: "Build"
      run: |
        # Windows AMD64
        env GOOS=windows GOARCH=amd64 go build
        zip -r vmn-windows-amd64.zip vmn

        # Windows ARM64
        env GOOS=windows GOARCH=arm64 go build
        zip -r vmn-windows-arm64.zip vmn

        # Linux AMD64
        env GOOS=linux GOARCH=amd64 go build
        tar -czvf vmn-linux-amd64.tar.gz vmn
        
        # Linux ARM64
        env GOOS=linux GOARCH=arm64 go build
        tar -czvf vmn-linux-arm64.tar.gz vmn

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.RELEASE_TOKEN }}"
        prerelease: false
        files: |
          *.tar.gz
